python fl_runner.py --conf fl-configs/report-configs/1a.yaml
python fl_runner.py --conf fl-configs/report-configs/1b.yaml
python fl_runner.py --conf fl-configs/report-configs/1c.yaml
python fl_runner.py --conf fl-configs/report-configs/1d.yaml
python fl_runner.py --conf fl-configs/report-configs/1e.yaml
python fl_runner.py --conf fl-configs/report-configs/2a.yaml
python fl_runner.py --conf fl-configs/report-configs/2b.yaml
python fl_runner.py --conf fl-configs/report-configs/3a.yaml
python fl_runner.py --conf fl-configs/report-configs/3b.yaml
python fl_runner.py --conf fl-configs/report-configs/3c.yaml
python fl_runner.py --conf fl-configs/report-configs/3d.yaml
python fl_runner.py --conf fl-configs/report-configs/4a.yaml
python fl_runner.py --conf fl-configs/report-configs/4b.yaml
python fl_runner.py --conf fl-configs/report-configs/4c.yaml
python fl_runner.py --conf fl-configs/report-configs/4d.yaml
python fl_runner.py --conf fl-configs/report-configs/4e.yaml
python fl_runner.py --conf fl-configs/report-configs/5a.yaml
python fl_runner.py --conf fl-configs/report-configs/6a.yaml
python fl_runner.py --conf fl-configs/report-configs/6b.yaml
python fl_runner.py --conf fl-configs/report-configs/6c.yaml
python fl_runner.py --conf fl-configs/report-configs/6d.yaml
python fl_runner.py --conf fl-configs/report-configs/6e.yaml
python fl_runner.py --conf fl-configs/report-configs/7a.yaml
python fl_runner.py --conf fl-configs/report-configs/7b.yaml
python fl_runner.py --conf fl-configs/report-configs/7c.yaml
python fl_runner.py --conf fl-configs/report-configs/7d.yaml
python fl_runner.py --conf fl-configs/report-configs/7e.yaml
